REGISTRATION_BUTTON = "//main//button[text()='Зарегистрироваться']"
EMAIL_BUTTON = "//main//label[text()='Email']/following-sibling::input"
PERSONAL_ACCOUNT_BUTTON = "//nav/a/p[text()='Личный Кабинет']"
ENTER_BUTTON_PERSONAL_ACCOUNT = "//main//button[text()='Войти']"
BUNS_BUTTON = "//main//span[text()='Булки']"
SAUSES_BUTTON = "//main//span[text()='Соусы']"
FILLING_BUTTON = "//main//span[text()='Начинки']"
KONSTRUKTOR_BUTTON = "//nav//p[text()='Конструктор']"
LOGO_BUTTON = "div[class*='header__logo'] a"
EXIT_BUTTON = "//nav//button[text()='Выход']"
LOGIN_WITH_BUTTON_ON_MAIN_PAGE = "//main//button[text()='Войти в аккаунт']"
FORGOT_PASSWORD_BUTTON = "//main//a[text()='Восстановить пароль']"
RESTORE_BUTTON = "//main//button[text()='Восстановить']"
ENTER_BUTTON_REGISTRATION_PAGE = "//main//a[text()='Войти']"